#!/usr/bin/env bash

# bspc monitor -d I II III IV V VI VII VIII
bspc monitor -d 1 2 3 4 5 6 7 8
# xrandr --output HDMI-1 --same-as eDP-1 --mode 1920x1080
xrandr --dpi 90 --output HDMI-0 --same-as HDMI-1 --mode 1920x1080

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# Nordic Colors
light_icy_blue="#E0F7FA"
snow_white="#FFFFFF"
sky_blue="#B3E5FC"
frosty_grey="#90A4AE"
cold_dark_grey="#607D8B"
icy_turquoise="#80DEEA"
frosted_red="#FF8A80"
fog="#CC2f343e"
background="#282828"

# Set background color for bspwm
bspc config background $background

# Window borders (Normal, Focused, Active)
bspc config border_width 2
bspc config normal_border_color $background
bspc config active_border_color $background
bspc config focused_border_color $cold_dark_grey

# Window gaps (optional)
bspc config window_gap 8

# Set workspace background colors
bspc config active_ws_bg_color $cold_dark_grey
bspc config inactive_ws_bg_color $background
bspc config urgent_ws_bg_color $frosted_red

# apps
bspc rule -a genymotion desktop=^4 stay
bspc rule -a zoom desktop=^4 stay
bspc rule -a pavucontrol state=floating
bspc rule -a Nwg-drawer state=floating state=fullscreen
bspc rule -a tint2 state=floating

#clean daemon
kill $(pgrep picom)
kill $(pgrep sxhkd)
kill $(pgrep dunst)
kill $(pgrep polybar)
kill $(pgrep clipmenud)
kill $(pgrep tint2)
kill $(pgrep xautolock)

#Autostart
feh --bg-scale $HOME/.config/bspwm/nord.jpg
picom --config $HOME/.config/picom/picom.conf &
sxhkd &
dunst &
polybar &
tint2 &
clipmenud &
xautolock -time 15 -locker "slock" -notify 30 -notifier "sleep 30 && systemctl suspend" &
